#!/bin/bash

set -e

L=$1
grid=$2
split=$3
ranks=${4:-1}
startstep=${5:-0}
endstep=${6:-1}
vars=$7
tag=$8
extra_args=$9

# create dir for distribution results
mkdir -p data/experiments/gray-scott/gs${L}_1000${tag}

for var in $vars
do

    varname=$var


    for (( i=$startstep; i<$endstep; i++ ))
    do
        num=`printf "%03d" $i`
        mpiexec -n $ranks ./data_dist.py -s ${grid} -r ${split} -m ${grid} -t float64 -c sz3 -b 1e-2 -j --step $i --var ${varname} --adios2xml ../adiosvm/Tutorial/gray-scott/adios2.xml  --adios2refname SimulationOutput ${extra_args} ../adiosvm/Tutorial/gray-scott/data/experiment/adios_v2.10/gs${L}_10000.bp | tee tmp.json | ./filter_proc_size sz3 | sort -n > data/experiments/gray-scott/gs${L}_1000${tag}/${varname}_$num.dist
    done
done

exit

varname=U

for (( i=0; i<$steps; i++ ))
do
    num=`printf "%03d" $i`
    mpirun -n $ranks ./data_dist.py -s ${grid} -r ${split} -m ${grid} -t float64 -c sz3 -b 1e-2 -j --step $i --var ${varname} --adios2xml ../adiosvm/Tutorial/gray-scott/adios2.xml  --adios2refname SimulationOutput ${extra_args} ../adiosvm/Tutorial/gray-scott/data/experiment/adios_v2.10/gs${L}_10000.bp | ./filter_proc_size sz3 | sort -n > data/experiments/gray-scott/gs${L}_1000/${varname}_$num.dist
done
