#!/bin/bash

set -e

L=$1
grid=$2
split=$3
ranks=${4:-1}
startstep=${5:-0}
endstep=${6:-1}
vars=$7
tag=$8
dataset=$9
adiosxml=${10}
outdir=${11}
extra_args=${12}

# create dir for distribution results
mkdir -p ${outdir}${tag}

for var in $vars
do

    varname=$var


    for (( i=$startstep; i<$endstep; i++ ))
    do
        num=`printf "%03d" $i`
        mpiexec -n $ranks ./data_dist.py \
		-s ${grid} -r ${split} -m ${grid} -t float64 -c sz3 -b 1e-2 -j --step $i \
		--var ${varname} \
		--adios2xml $adiosxml  --adios2refname SimulationOutput \
		${extra_args} \
		${dataset} \
		| ./filter_proc_size sz3 | sort -n > ${outdir}${tag}/${varname}_$num.dist
    done
done
